config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/new_admin'
  post 'admin/new_admin', to: 'admin#make_admin'
  get 'settings/display', to: 'settings#display', as: 'settings'
  get 'carretes/services'
  delete 'servicio/destroy_from_profile', to: 'servicio#destroy_from_profile'
  delete 'carretes/destroy_from_profile', to: 'carretes#destroy_from_profile'
  get 'settings/display'
  get 'settings/index'
  get 'settings/new'
  get 'settings/edit'
  get 'comunas/index'
  get 'comunas/show'
  get 'comunas/new'
  get 'comunas/edit'
  get 'servicio/index'
  get 'servicio/new'
  get 'servicio/show'
  get 'servicio/edit'
  get 'carretes/new'
  get 'carretes/index'
  get 'carretes/show'
  get 'carretes/edit'
  get 'carretes/filter'
  get 'profile/profile'
  get 'profile/add_descripcion'
  get 'home_page/home'
  get 'postulacions/close_postulacion'
  get 'carretes/mark_done'

  resources :comunas
  resources :admin

  put 'go_to_profile' => 'profile#profile'
  get 'profile/redir'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  match '/users/:id' => 'profile#make_admin', :via => :get
  match '/profile/blabla' => 'profile#make_service', :via => :get
  match '/users/:id' => 'profile#destroy', :via => :delete, :as => :user

  post 'postulacion' => 'postulacions#postular'
  post 'add_descrpicon' => 'prfoile#add_descripcion'

  resources :carretes do
    resources :comentarios
    resources :postulacion
    # get 'carretes/:id/comentarios_carrete'
  end

  get '/servicio/admin_index' => 'servicio#admin_index'
  get '/servicio/aprobar' => 'servicio#aprobar'

  resources :servicio do
    resources :servicecomments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home_page/home'
  root 'home_page#home'
end

app/models/carrete.rb
# frozen_string_literal: true

class Carrete < ApplicationRecord
  belongs_to :user
  has_many :comentarios, dependent: :destroy
  has_one :postulacion
  has_many :carrete_servicio, dependent: :destroy
  has_many :servicios, through: :carrete_servicio

  def get_id
    read_attribute(:id)
  end
end

app/models/carrete_servicio.rb
# frozen_string_literal: true

class CarreteServicio < ApplicationRecord
  belongs_to :carrete
  belongs_to :servicio
end

app/models/comentario.rb
# frozen_string_literal: true

class Comentario < ApplicationRecord
  belongs_to :carrete
  belongs_to :user
  # attr_accessor :author, :body
end

app/models/comuna.rb
# frozen_string_literal: true

class Comuna < ApplicationRecord
  has_many :users
  has_many :cobertura_servicio, dependent: :destroy
  has_many :servicios, through: :cobertura_servicio
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :comentarios,:dependent => :destroy
	# attr_accessor :comentarios
	validates :author, :title, :tipo, :comment, presence: true

	def author_and_title_and_tipo
		"#{author} #{title} #{tipo}"
	end

end

app/models/postulacion.rb
# frozen_string_literal: true

class Postulacion < ApplicationRecord
  belongs_to :carrete
  serialize :postulaciones, Hash

  def update_carrete_id(id)
    update(carrete_id: id)
  end

  def update_postulaciones(postulaciones)
    update(postulaciones: postulaciones)
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_many :users
end

app/models/servicecomment.rb
# frozen_string_literal: true

class Servicecomment < ApplicationRecord
  belongs_to :user
  belongs_to :servicio
end

app/models/servicio.rb
# frozen_string_literal: true

class Servicio < ApplicationRecord
  belongs_to :user
  has_many :servicecomments, dependent: :destroy
  has_many :cobertura_servicio, dependent: :destroy
  has_many :carrete_servicio, dependent: :destroy
  has_many :comunas, through: :cobertura_servicio
  has_many :carretes, through: :carrete_servicio
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :carretes
  has_many :comentarios
  has_many :servicios
  has_many :servicecomments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :set_default_role
  belongs_to :role, optional: true

  def update_role(role)
    update(role_id: role)
  end

  private

  def set_default_role
    update(role_id: Role.find_by(code: 'default').id)
  end
end

app/models/user_descripcion.rb
# frozen_string_literal: true

class UserDescripcion < ApplicationRecord
end

app/controllers/carretes_controller.rb
# frozen_string_literal: true

class CarretesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit index show]
  def new
    @carrete = Carrete.new
  end

  def create
    @carrete = Carrete.new(carrete_params)
    @carrete.user = current_user

    if @carrete.save
      @postulacion = Postulacion.new
      @postulacion.update_carrete_id(@carrete.id)
      @postulacion.save
      redirect_to carretes_index_path, notice: 'Carrete creado con exito'
    else
      render :new
    end
  end

  def index
    @carrete = if params[:filter]
                  if (params[:precio_min] != "")
                    Carrete.where('comuna_id=' + params[:comunas_id] + ' AND ' +  'min_price >' + params[:precio_min])
                  else
                    Carrete.where(comuna_id: params[:comunas_id] )
                  end
               else
                 Carrete.all
               end
    @carrete
  end

  
  def show
    @carrete = Carrete.find(params[:id])
    id_carrete = @carrete.id.dup
    @postulacion = Postulacion.find_by(carrete_id: id_carrete)
    @monto = 0
    @postulacion.postulaciones.each do |_key, value|
      @monto += value.to_i
    end
  end

  def services
    @carrete = Carrete.find(params[:id])
    @comuna = Comuna.find(@carrete.comuna_id)
    @servicio = @comuna.servicios
  end

  def edit
    @carrete = Carrete.find(params[:id])
  end

  def update
    @carrete = Carrete.find(params[:id])
    if params[:carrete][:servicio]
      @carrete.servicios << Servicio.find(params[:carrete][:servicio])
    end
    if @carrete.update_attributes(carrete_params)
      redirect_to carretes_index_path, confirm: 'Carrete editado con exito'
    else
      render 'edit'
    end
  end

  def mark_done
    @carrete = Carrete.find(params[:id])
    @carrete.done = true
    @carrete.save
  end

  def destroy
    @carrete = Carrete.find(params[:id])
    @carrete.destroy
    redirect_to carretes_index_path, notice: 'Carrete borrado con exito'
  end

  def destroy_from_profile
    @carrete = Carrete.find(params[:id])
    @carrete.destroy
    redirect_to profile_profile_path, confirm: 'Carrete borrado con exito'
  end

  def carrete_params
    params.require(:carrete).permit(:title, :body, :fecha, :comuna_id, :direccion,
                                    :capacidad_maxima, :user, :max_price, :min_price)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/carretes_helper.rb
# frozen_string_literal: true

module CarretesHelper
end

app/helpers/comunas_helper.rb
# frozen_string_literal: true

module ComunasHelper
end

app/helpers/meme_helper.rb
# frozen_string_literal: true

module MemeHelper
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/servicio_helper.rb
# frozen_string_literal: true

module ServicioHelper
end

app/helpers/settings_helper.rb
# frozen_string_literal: true

module SettingsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/carretes/edit.html.erb


<div class="hero is-fullheight is-light is-bold">
  <br>
  <div class="columns">
    <div class="column is-one-quarter">
    </div>
    <div class="column is-half">
      <div class="card">
        <div class="card-content">
          <h1 class= "title has-text-centered"> Edita tu Carrete<h1>
          <%= form_for :carrete, :url => { :action => :update, :id => @carrete.id },
          :method => :put do |f| %>
            <div class='columns'>
            <div class='column'>
            <% if @carrete.errors.any? %>
              <div id="errorExplanation">
                <h2><%= pluralize(@carrete.errors.count, "error") %> prohibited
                  this servicio from being saved:</h2>
                <ul>
                <% @carrete.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
              <% end %>
              <p><%= f.label :title, 'Titulo: ' %><br><%= f.text_field :title, class: 'input is-info' %></p>
              <p><%= f.label :body, 'Descripción: ' %><br><%= f.text_area :body, class: "textarea is-info", rows: 10 %></p>
              <p><%= f.label :fecha, 'Fecha del Carrete: ' %><%= f.date_field :fecha, class: 'input is-info' %></p>
              <%= f.label :Comuna %><br />
              <div class = "select is-info">
						    <%= f.select :comuna_id, Comuna.all.collect { |p| [ p.nombre, p.id ] }%>
					    </div>
              <p><%= f.label :direccion, 'Dirección (calle): ' %><%= f.text_field :direccion, class: 'input is-info' %></p>
              <p><%= f.label :capacidad_maxima, 'Capacidad Máxima de asistentes: ' %><%= f.text_field :capacidad_maxima, class: 'input is-info' %></p>
              <p><%= f.label :max_price, 'Precio máximo de ingreso: ' %><%= f.text_field :max_price, class: 'input is-info' %></p>
              <p><%= f.label :min_price, 'Precio mínimo de ingreso: ' %><%= f.text_field :min_price, class: 'input is-info' %></p>
              <footer class="card-footer">
                <div class="card-footer-item">
                <%= f.submit 'Guardar cambios', class: "button is-primary" %>
                </div>
                <div class="card-footer-item">
					<%= link_to "Cancelar", carretes_index_url, class: "button is-link" %>
					<br>
					</div>
                </footer>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>      

app/views/carretes/index.html.erb
 <% @image_dict = {1 => "https://www.ctvnews.ca/polopoly_fs/1.5063738.1597360423!/httpImage/image.jpg_gen/derivatives/landscape_1020/image.jpg",
				  2 =>  "https://i2.wp.com/www.society19.com/uk/wp-content/uploads/sites/5/2019/04/uk-1231-920337-0-front.jpg?fit=%2C&ssl=1",
				  3 =>  "https://www.thespruce.com/thmb/pE5Jk1wtueXSKrpm52bv5GFFOvg=/1800x1012/smart/filters:no_upscale()/GettyParty-5b35eb3c46e0fb003788537e.jpg",
				  4 =>  "https://www.electronicbeats.net/app/uploads/2017/04/arma17_club.jpg"}  %>
<style>
 .column {
  gap: flex;
}
.card .card-image,
.card .card-image .image img {
  height: 170px;
}

label {
    /* Other styling... */
    text-align: right;
    clear: both;
    float:left;
    margin-right:15px;
}

</style>

 <div class="hero is-fullheight is-light is-bold">
  <br>
<h1 class= "title is-2 has-text-centered">Carretes disponibles</h1>
<div class= "columns is-centered">
<%= link_to 'Crear Carrete', carretes_new_url, class: "button is-primary"%>
</div>

<%= form_with :url => { :action => :index}, method: "get" ,local: true do |f| %>
                    <div class="columns is-centered">
                    <div class ="column is-one-third" >
                    <div class="card">   
                    <div class="card-content">   
                    <div class="field is-horizontal">
                      <div class="field-label ">
                        <label class="label">Comuna</label>
                      </div>
                      <div class="field-body">
                        <div class="field">
                          <div class="control">
                              <div class = "select">
                                <%= f.hidden_field :filter, :value => true %>
                                <%= f.select :comunas_id, Comuna.all.collect { |p| [ p.nombre, p.id ] }%>
                              </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="field is-horizontal">
                      <div class="field-label">
                        <label class="label">Precio minimo</label>
                      </div>
                      <div class="field-body">
                        <div class="field">
                          <div class="control">
                            <%= text_field_tag :precio_min, nil, class: "input"%>  
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="actions has-text-centered">
                      <%= f.submit "Filtrar", class: "button is-info " %>
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
    <%end%>
<br>
<div class="carrete-list is-centered">
<div class="columns is-multiline is-centered is-3">
<% @i = 0%>
	<% @carrete.each do |carrete| %>
	<% @i += 1%>
	<% if @i == 5%>
	<% @i = 1%>
	<% end%>
    <div class="column is-one-quarter">
	<div class="card is-half">
  <header class="card-header">
    <p class="card-header-title">
      <%= carrete.title%>
    </p>
	<a href="#" class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </a>
  </header>
  <div class="card-image is-260x130">
    <figure class="image is-260x130">
      <img src=<%=@image_dict[@i]%> alt="Placeholder image">
    </figure>
	 </div>
  <div class="card-content">
    <div class="content">
      <b>Comuna:</b> <%= Comuna.find(carrete.comuna_id).nombre %>
      <br>
	  <b>Creado por:</b> <%= carrete.user.name%>
	  <br>
    <b>Fecha: </b> <%= carrete.fecha%>
    </div>
  </div>
  <footer class="card-footer">
	<%= link_to 'Abrir', carretes_show_url(id: carrete.id), class: "card-footer-item" %></
  </footer>
  
</div>
</div>

	<% end %>
	</div>
</div>
 </div>

app/views/carretes/new.html.erb




<div class="hero is-fullheight is-light is-bold">
<br>
	<div class='columns'>

		<div class='column is-one-quarter'>
		</div>

		<div class='column is-half'>
			<div class="card">
				<div class="card-content">
					<h1 class= "title has-text-centered">Crea tu Carrete</h1>
					<% if @carrete.errors.any? %>
					<div>
						Se encontraron errores:
						<ul>
							<% @carrete.errors.full_messages.each do |error_message| %>
							<li><%= error_message %></li>
							<% end %>
						</ul>
					</div>
					<% end %>
					<%= form_with model: @carrete, :url => { :action => :create }, local: true do |f| %>
					<div class='columns'>
            		<div class='column'>
					<p>
					<%= f.label :title, 'Titulo: ' %>
					<br>
					<%= f.text_field :title, class: 'input is-info' %>
					</p>
					<p>
					<%= f.label :body, 'Descripción: ' %>
					<br>
					<%= f.text_area :body, class: "textarea is-info", rows: 10 %>
					</p>
					<p>
					<%= f.label :fecha, 'Fecha del Carrete: ' %>
					<br>
					<%= f.date_field :fecha, class: 'input is-info' %>
					</p>
					<%= f.label :Comuna %><br />
					<div class = "select is-info">
						<%= f.select :comuna_id, Comuna.all.collect { |p| [ p.nombre, p.id ] } %>
					</div>
					<p><%= f.label :direccion, 'Dirección (calle): ' %><br><%= f.text_field :direccion, class: 'input is-info' %></p>
					<p><%= f.label :capacidad_maxima, 'Capacidad Máxima de asistentes: ' %><br><%= f.text_field :capacidad_maxima, class: 'input is-info' %></p>
					<p><%= f.label :max_price, 'Precio máximo de ingreso: ' %><br><%= f.text_field :max_price, class: 'input is-info' %></p>
					<p><%= f.label :min_price, 'Precio mínimo de ingreso: ' %><br><%= f.text_field :min_price, class: 'input is-info' %></p>
					<footer class="card-footer">
              		<div class="card-footer-item">
					<%= f.submit "Crear Carrete", class:'button is-primary' %>
					</div>
					<div class="card-footer-item">
					<%= link_to "Cancelar", carretes_index_url, class: "button is-link" %>
					<br>
					</div>
              		</footer> 
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>	
</div>

app/views/carretes/services.html.erb
<% @image_dict = {1 => "https://wherelunch.files.wordpress.com/2015/02/ruta_cocteleria_.jpg",
				  2 =>  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScXDEHPaU_36C1D6A27BRsVOPcTcz_fDtxHw&usqp=CAU",
				  3 =>  "https://www.thespruce.com/thmb/pE5Jk1wtueXSKrpm52bv5GFFOvg=/1800x1012/smart/filters:no_upscale()/GettyParty-5b35eb3c46e0fb003788537e.jpg",
				  4 =>  "https://www.electronicbeats.net/app/uploads/2017/04/arma17_club.jpg"}  %>

<style>
 .column {
  gap: flex;
}
.card .card-image,
.card .card-image .image img {
  height: 170px;
}
</style>

<div class="hero is-fullheight is-light is-bold">
  <br>
<h1 class= "title is-2 has-text-centered">Servicios disponibles en <%=@comuna.nombre%></h1>

<br></br>

<div class="servicio-list is-centered">
<div class="columns is-multiline is-centered is-3">
<% @i = 0%>
	<% @servicio.each do |servicio| %>
	<% @i += 1%>
	<% if @i == 5%>
	<% @i = 1%>
	<% end%>
<div class="column is-one-quarter">
	<div class="card is-half">
  <header class="card-header">
    <p class="card-header-title">
      <%= servicio.title%>
    </p>
	<a href="#" class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </a>
  </header>
  <div class="card-image is-260x130">
    <figure class="image is-260x130">
      <img src=<%=@image_dict[@i]%> alt="Placeholder image">
    </figure>
	 </div>
  <div class="card-content">
    <div class="content">
	  <b>Comuna(s):</b> <% servicio.comunas.each do |comuna|%>
	  <%=comuna.nombre%>
	  <% end %>
	  <br>
	  <b>Descripción:</b> <%= servicio.body %>
	  <br>
	  <b>Precio:</b> <%= servicio.price %>
    </div>
  </div>
  <footer class="card-footer">
  
	<%= link_to 'Abrir', servicio_show_url(id: servicio.id), class: "card-footer-item" %>
 <div class='card-footer-item'>
	<%= form_with model: @carrete, local: true do |f| %>
    <%= f.hidden_field :servicio, :value => servicio.id %>
    <%= f.submit 'Contratar', class: "button is-link is-outlined"  %>
	<% end %>
  </div>
  </footer>
  
</div>
</div>

	<% end %>
	</div>
</div>
 </div>

app/views/carretes/show.html.erb
<div class="hero is-fullheight is-light is-bold">
 <br>
  <div class="columns ">
    <div class="column">
      <div class="columns ">
        <div class="column is-one-quarter">
        </div>
        <div class="column is-half">
          <div class="card">
            <div class="card-content">
                <p class="card-header-title">
                  <h1 class= "title has-text-centered"> <%= @carrete.title  %><h1>
                </p>
                <div class="columns">
                  <div class="column">
                    <p>
                      <strong>Descripción: </strong>
                      <%= @carrete.body %>
                    </p>

                    <p>
                      <strong>Precio máximo de ingreso: <%= @carrete.max_price %></strong>
                    </p>

                    <p>
                      <strong>Precio minimo de ingreso: <%= @carrete.min_price %></strong>
                    </p>
                    <p>
                      <strong>Capacidad Máxima: <%= @carrete.capacidad_maxima %></strong>
                    </p>
                    </span>
                  </div>
                    
                  <div class="column">
                    <span class = "has-text-right">
                    <p>
                      <strong>Autor: </strong>
                      <%= @carrete.user.name %>
                    </p>

                    <p>
                      <strong>Fecha del evento: <%= @carrete.fecha %></strong>
                    </p>

                    <p>
                      <strong>Comuna(s): </strong>
                      <%= Comuna.find(@carrete.comuna_id).nombre%>
                    </p>
                    
                  </div>
                  <div class="column is-one-quarter">
                    <%= link_to "Volver", carretes_index_url, class: "button is-primary is-fullwidth" %>
                    <br>
              	   <%if @carrete.user == current_user%>
                    <%= link_to 'Modificar', carretes_edit_url(id: @carrete.id), class:"button is-link is-fullwidth"%>
                    <br>
                    <%= link_to 'Eliminar', { :action => :destroy, :id => @carrete.id }, 
                    :method => :delete, :data => { :confirm => 'Are you sure?' } , 
                    class: "button is-danger is-fullwidth"%>
                   <%end%>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
      <div class="columns">
          <div class="column is-one-quarter">
          </div>
          <div class="column is-one-quarter">
            <div class="card">
              <div class="card-content">
                <h2 class="title is-4 has-text-centered">Postular</h2>
        
                <%= form_for(@postulacion, {:controller => "postulacions", :action => "postular", :method => "post"}) do |f| %>
                    <p>
                    <%= f.hidden_field :id, :value => @postulacion.id %>
                    <%= f.hidden_field :carrete_id, :value => @carrete.id %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>       
                    <%= f.label "Ingrese monto", class: "is-size-5" %><br />
                    <%= text_field_tag :monto, nil, class: "input" %>  
                    <br>
                    <br>
                    <p>
                    <% if @postulacion.is_open == 0%>
                      <button class="button is-danger is-fullwidth" title="Disabled button" disabled>Postulaciones Cerradas</button>
                    <% else%>
                      <%= f.submit "Postular", class: "button is-success is-fullwidth" %>
                      </p>
                    <% end%>
                <% end %>
              </div>
            </div>
            <br>
            <div class="card">
              <div class="card-content">
            <p class="card-header-title">
                <h1 class= "title has-text-centered"> Servicios contratados<h1>
            </p>
                <ul>
                <%@carrete.servicios.each do |servicio|%>
                <li><%=link_to servicio.title+' por '+servicio.user.name, servicio_show_url(id: servicio.id), class: "button is-ghost is-fullwidth"%></li>
                <%end%>
                </ol>
                </p>
            </div>
          </div>
          </div>
          <div class="column is-one-quarter">
          <%if @carrete.user == current_user%>
            <div class="card">
              <div class="card-content">
                <p class="card-header-title">
                    <h1 class= "title has-text-centered"> Info Secreta<h1>
                </p>
                <p>
                  <h2 class= "subtitle has-text-centered"><strong>Postulantes: <%= @postulacion.postulaciones.count %></strong></h2>
                </p>

                <h2 class= "subtitle has-text-centered"> <strong>Monto acumulado fiesta <strong></h2>
                <h2 class= "subtitle has-text-centered"><%="$" + @monto.to_s %></h2>
                <% if @postulacion.is_open == 0%>
                  <button class="button is-danger is-fullwidth" title="Disabled button" disabled>Postulaciones Cerradas</button>
                <% else%>
                  <%= form_with(url: "/postulacions/close_postulacion", method: "get") do |f| %>
                    <p>
                    <%= f.hidden_field :id, :value => @postulacion.id %>
                    <%= f.hidden_field :carrete_id, :value => @carrete.id %>
                    </p>
                    <p>
                    <%= f.submit "Cerrar Postulación", class: "button is-danger is-fullwidth" %>
                    </p>
                  <% end %>
                <% end %>
                <br>
                <%if !@carrete.done %>
                <p>
                <%= link_to 'Contratar servicio', carretes_services_url(id: @carrete.id), class: "button is-success is-fullwidth"%>
                </p>
                <br>
                  <%= form_with(url: "/carretes/mark_done", method: "get") do |f| %>
                    <p>
                    <%= f.hidden_field :id, :value => @carrete.id %>
                    <%= f.submit "Marcar realizado", class: "button is-success is-fullwidth"%>
                    </p>
                  <% end %>
                <%else%> 
                  <button class="button is-danger is-fullwidth" title="Disabled button" disabled>Carrete Realizado</button>
                <% end %>
              </div>
            </div>
          <%end%>
          </div>
          
      </div>

      <div class="columns">
        <div class="column is-one-quarter">
        </div>
        <div class="column is-half">
          <% if @carrete.done%>
            <div class="card">
              <div class="card-content">
                <h2 class="title is-4 has-text-centered">Comentarios</h2>
                <% @carrete.comentarios.each do |comment| %>
                <div class = "container ">
                <article class="media">
                  <figure class="media-left">
                    <p class="image is-64x64">
                      <img src="https://i.pinimg.com/originals/d1/ad/13/d1ad13605acd060cbcc4b334e2119883.png">
                    </p>
                  </figure>
                  <div class="media-content">
                    <div class="content">
                      <p>
                        <b><%= comment.user.name %></b>
                        <br>
                        <%= comment.body %>
                      </p>
                    </div>
                    <nav class="level is-mobile">
                      <div class="level-left">
                        <a class="level-item">
                          <span class="icon is-small"><i class="fas fa-reply"></i></span>
                        </a>
                        <a class="level-item">
                          <span class="icon is-small"><i class="fas fa-retweet"></i></span>
                        </a>
                        <a class="level-item">
                          <span class="icon is-small"><i class="fas fa-heart"></i></span>
                        </a>
                      </div>
                    </nav>
                  </div>
                  <div class="media-right">
                    <% if comment.user == current_user || @carrete.user == current_user%>
                        <%= link_to '', [comment.carrete, comment],
                          :method => :delete,
                        :data => { :confirm => '¿Estás seguro?' }, class: 'delete' %>
                    <%end%>
                  </div>
                </article>
                <% end %>
                <%= form_for([@carrete, @carrete.comentarios.build]) do |f| %>
                <article class="media">
                  <figure class="media-left">
                    <p class="image is-64x64">
                      <img src="https://i.pinimg.com/originals/d1/ad/13/d1ad13605acd060cbcc4b334e2119883.png">
                    </p>
                  </figure>
                  <div class="media-content">
                    <div class="field">
                      <p class="control">
                        <%= f.text_area :body, class: "textarea", placeholder: "Escribe tu comentario..." %>
                      </p>
                    </div>
                    <nav class="level">
                      <div class="level-left">
                        <div class="level-item">
                          <a >
                          <%= f.submit 'Enviar', class: "button is-info" %>
                          </a>
                        </div>
                      </div>
                    </nav>
                  </div>
                </article>
                <% end %>
              </div>
            </div> 
          <%end%> 
        </div>       
      </div>
    </div>  
  </div>
</div>
  

