config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/new_admin'
  post 'admin/new_admin', to: 'admin#make_admin'
  get 'settings/display', to: 'settings#display', as: 'settings'
  get 'carretes/services'
  delete 'servicio/destroy_from_profile', to: 'servicio#destroy_from_profile'
  delete 'carretes/destroy_from_profile', to: 'carretes#destroy_from_profile'
  get 'settings/display'
  get 'settings/index'
  get 'settings/new'
  get 'settings/edit'
  get 'comunas/index'
  get 'comunas/show'
  get 'comunas/new'
  get 'comunas/edit'
  get 'servicio/index'
  get 'servicio/new'
  get 'servicio/show'
  get 'servicio/edit'
  get 'carretes/new'
  get 'carretes/index'
  get 'carretes/show'
  get 'carretes/edit'
  get 'carretes/filter'
  get 'profile/profile'
  get 'profile/add_descripcion'
  get 'home_page/home'
  get 'postulacions/close_postulacion'
  get 'carretes/mark_done'

  resources :comunas
  resources :admin

  put 'go_to_profile' => 'profile#profile'
  get 'profile/redir'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  match '/users/:id' => 'profile#make_admin', :via => :get
  match '/profile/blabla' => 'profile#make_service', :via => :get
  match '/users/:id' => 'profile#destroy', :via => :delete, :as => :user

  post 'postulacion' => 'postulacions#postular'
  post 'add_descrpicon' => 'prfoile#add_descripcion'

  resources :carretes do
    resources :comentarios
    resources :postulacion
    # get 'carretes/:id/comentarios_carrete'
  end

  get '/servicio/admin_index' => 'servicio#admin_index'
  get '/servicio/aprobar' => 'servicio#aprobar'

  resources :servicio do
    resources :servicecomments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home_page/home'
  root 'home_page#home'
end

app/models/carrete.rb
# frozen_string_literal: true

class Carrete < ApplicationRecord
  belongs_to :user
  has_many :comentarios, dependent: :destroy
  has_one :postulacion
  has_many :carrete_servicio, dependent: :destroy
  has_many :servicios, through: :carrete_servicio

  def get_id
    read_attribute(:id)
  end
end

app/models/carrete_servicio.rb
# frozen_string_literal: true

class CarreteServicio < ApplicationRecord
  belongs_to :carrete
  belongs_to :servicio
end

app/models/comentario.rb
# frozen_string_literal: true

class Comentario < ApplicationRecord
  belongs_to :carrete
  belongs_to :user
  # attr_accessor :author, :body
end

app/models/comuna.rb
# frozen_string_literal: true

class Comuna < ApplicationRecord
  has_many :users
  has_many :cobertura_servicio, dependent: :destroy
  has_many :servicios, through: :cobertura_servicio
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :comentarios,:dependent => :destroy
	# attr_accessor :comentarios
	validates :author, :title, :tipo, :comment, presence: true

	def author_and_title_and_tipo
		"#{author} #{title} #{tipo}"
	end

end

app/models/postulacion.rb
# frozen_string_literal: true

class Postulacion < ApplicationRecord
  belongs_to :carrete
  serialize :postulaciones, Hash

  def update_carrete_id(id)
    update(carrete_id: id)
  end

  def update_postulaciones(postulaciones)
    update(postulaciones: postulaciones)
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_many :users
end

app/models/servicecomment.rb
# frozen_string_literal: true

class Servicecomment < ApplicationRecord
  belongs_to :user
  belongs_to :servicio
end

app/models/servicio.rb
# frozen_string_literal: true

class Servicio < ApplicationRecord
  belongs_to :user
  has_many :servicecomments, dependent: :destroy
  has_many :cobertura_servicio, dependent: :destroy
  has_many :carrete_servicio, dependent: :destroy
  has_many :comunas, through: :cobertura_servicio
  has_many :carretes, through: :carrete_servicio
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :carretes
  has_many :comentarios
  has_many :servicios
  has_many :servicecomments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :set_default_role
  belongs_to :role, optional: true

  def update_role(role)
    update(role_id: role)
  end

  private

  def set_default_role
    update(role_id: Role.find_by(code: 'default').id)
  end
end

app/models/user_descripcion.rb
# frozen_string_literal: true

class UserDescripcion < ApplicationRecord
end

app/controllers/comunas_controller.rb
# frozen_string_literal: true

class ComunasController < ApplicationController
  before_action :authenticate_user!, only: %i[index new edit]
  def create
    @comuna = Comuna.new(comuna_params)

    if @comuna.save
      redirect_to comunas_path, notice: 'Comuna agregada con éxito'
    else
      render :new
    end
  end

  def index
    @comuna = Comuna.order(:nombre)
  end

  def new
    @comuna = Comuna.new
  end

  def edit
    @comuna = Comuna.find(params[:id])
  end

  def destroy
    @comuna = Comuna.find(params[:id])
    @comuna.destroy
    redirect_to comunas_index_path, notice: 'Comuna borrada con exito'
  end

  def update
    @comuna = Comuna.find(params[:id])

    if @comuna.update(comuna_params)
      redirect_to @comuna
    else
      render 'edit'
    end
  end

  private

  def comuna_params
    params.require(:comuna).permit(:nombre)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/carretes_helper.rb
# frozen_string_literal: true

module CarretesHelper
end

app/helpers/comunas_helper.rb
# frozen_string_literal: true

module ComunasHelper
end

app/helpers/meme_helper.rb
# frozen_string_literal: true

module MemeHelper
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/servicio_helper.rb
# frozen_string_literal: true

module ServicioHelper
end

app/helpers/settings_helper.rb
# frozen_string_literal: true

module SettingsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/comunas/edit.html.erb
<%if current_user.role_id!=2%>
<script type='text/javascript'>
    window.location.href="/";
    window.alert("No tienes permisos");
</script>
<%end%>
<h1><%=@comuna.nombre%></h1>

<%= form_with(model: @comuna, local: true) do |form| %>

  <% if @comuna.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comuna.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @comuna.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>


<%= link_to 'Volver', comunas_path %>

app/views/comunas/index.html.erb
<%if current_user.role_id!=2%>
<script type='text/javascript'>
    window.location.href="/";
    window.alert("No tienes permisos");
</script>
<%end%>
<div class="hero is-fullheight is-light is-bold">
<div class='body'>
    <div class="columns is-centered">
        <div class='column is-one-quarter'>
        <div class=card>
        <div class='card-content has-text-centered'>
        
            <h1 class= "title has-text-centered">Comunas</h1>

            <%=link_to "Agregar comuna", comunas_new_path, class: 'button is-link'%>
            <br>
            <br>
            <ul class="comuna list">
                <% @comuna.each do |comuna| %>
                    <div class=content>
                        
                        <div class='columns'>
                        <div class='column is-three-fifths has-text-left'>
                            <li class='subtitle is-5'><%= comuna.nombre%>
                            </div>
                            <div class='column is-half'>
                            <%= link_to 'Eliminar',
                                    { :action => :destroy, :id => comuna.id }, 
                                    :method => :delete, 
                                    :data => { :confirm => 'Are you sure?' }, class: "button is-danger"
                                        %></div>
                                        </li>
                                        
                                       
                                       
                        </div>
                <% end %>
            </ul>
            
       
        
        </div>
        </div>
    </div>
</div>
</div>


app/views/comunas/new.html.erb

<%if current_user.role_id!=2%>
<script type='text/javascript'>
    window.location.href="/";
    window.alert("No tienes permisos");
</script>
<%end%>
<div class="hero is-fullheight is-light is-bold">

    <div class="columns is-centered">
        <div class='column is-one-fifth'>
            <div class='card'>
                <div class='card-content'>

<h1 class= "title has-text-centered">Nueva comuna</h1>



<%= form_with model: @comuna, :url => { :action => :create } do |f| %>
 <p><%= f.label :nombre, 'Nombre: '%>
 <%= f.text_field :nombre, class: 'input is-info' %></p>
 <footer class="card-footer">
              
              <div class="card-footer-item">
              <%= f.submit "Agregar", class:'button is-success' %>
              </div>
             
</footer>
  
 <% end %>

</div>
            </div>
        </div>
    </div>
</div>

app/views/comunas/show.html.erb
<%if current_user.role_id!=2%>
<script type='text/javascript'>
    window.location.href="/";
    window.alert("No tienes permisos");
</script>
<%end%>
<h1><%=@comuna.nombre%></h1>


<%= link_to 'Editar', edit_comuna_url(@comuna)%>
<br>
<%= link_to 'Eliminar',
         { :action => :destroy, :id => @comuna.id }, 
         :method => :delete, 
         :data => { :confirm => 'Are you sure?' }
             %>