config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/new_admin'
  post 'admin/new_admin', to: 'admin#make_admin'
  get 'settings/display', to: 'settings#display', as: 'settings'
  get 'carretes/services'
  delete 'servicio/destroy_from_profile', to: 'servicio#destroy_from_profile'
  delete 'carretes/destroy_from_profile', to: 'carretes#destroy_from_profile'
  get 'settings/display'
  get 'settings/index'
  get 'settings/new'
  get 'settings/edit'
  get 'comunas/index'
  get 'comunas/show'
  get 'comunas/new'
  get 'comunas/edit'
  get 'servicio/index'
  get 'servicio/new'
  get 'servicio/show'
  get 'servicio/edit'
  get 'carretes/new'
  get 'carretes/index'
  get 'carretes/show'
  get 'carretes/edit'
  get 'carretes/filter'
  get 'profile/profile'
  get 'profile/add_descripcion'
  get 'home_page/home'
  get 'postulacions/close_postulacion'
  get 'carretes/mark_done'

  resources :comunas
  resources :admin

  put 'go_to_profile' => 'profile#profile'
  get 'profile/redir'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  match '/users/:id' => 'profile#make_admin', :via => :get
  match '/profile/blabla' => 'profile#make_service', :via => :get
  match '/users/:id' => 'profile#destroy', :via => :delete, :as => :user

  post 'postulacion' => 'postulacions#postular'
  post 'add_descrpicon' => 'prfoile#add_descripcion'

  resources :carretes do
    resources :comentarios
    resources :postulacion
    # get 'carretes/:id/comentarios_carrete'
  end

  get '/servicio/admin_index' => 'servicio#admin_index'
  get '/servicio/aprobar' => 'servicio#aprobar'

  resources :servicio do
    resources :servicecomments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home_page/home'
  root 'home_page#home'
end

app/models/carrete.rb
# frozen_string_literal: true

class Carrete < ApplicationRecord
  belongs_to :user
  has_many :comentarios, dependent: :destroy
  has_one :postulacion
  has_many :carrete_servicio, dependent: :destroy
  has_many :servicios, through: :carrete_servicio

  def get_id
    read_attribute(:id)
  end
end

app/models/comentario.rb
# frozen_string_literal: true

class Comentario < ApplicationRecord
  belongs_to :carrete
  belongs_to :user
  # attr_accessor :author, :body
end

app/models/comuna.rb
# frozen_string_literal: true

class Comuna < ApplicationRecord
  has_many :users
  has_many :cobertura_servicio, dependent: :destroy
  has_many :servicios, through: :cobertura_servicio
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :comentarios,:dependent => :destroy
	# attr_accessor :comentarios
	validates :author, :title, :tipo, :comment, presence: true

	def author_and_title_and_tipo
		"#{author} #{title} #{tipo}"
	end

end

app/models/postulacion.rb
# frozen_string_literal: true

class Postulacion < ApplicationRecord
  belongs_to :carrete
  serialize :postulaciones, Hash

  def update_carrete_id(id)
    update(carrete_id: id)
  end

  def update_postulaciones(postulaciones)
    update(postulaciones: postulaciones)
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_many :users
end

app/models/servicecomment.rb
# frozen_string_literal: true

class Servicecomment < ApplicationRecord
  belongs_to :user
  belongs_to :servicio
end

app/models/servicio.rb
# frozen_string_literal: true

class Servicio < ApplicationRecord
  belongs_to :user
  has_many :servicecomments, dependent: :destroy
  has_many :cobertura_servicio, dependent: :destroy
  has_many :carrete_servicio, dependent: :destroy
  has_many :comunas, through: :cobertura_servicio
  has_many :carretes, through: :carrete_servicio
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :carretes
  has_many :comentarios
  has_many :servicios
  has_many :servicecomments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :set_default_role
  belongs_to :role, optional: true

  def update_role(role)
    update(role_id: role)
  end

  private

  def set_default_role
    update(role_id: Role.find_by(code: 'default').id)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/carretes_helper.rb
# frozen_string_literal: true

module CarretesHelper
end

app/helpers/comunas_helper.rb
# frozen_string_literal: true

module ComunasHelper
end

app/helpers/meme_helper.rb
# frozen_string_literal: true

module MemeHelper
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/servicio_helper.rb
# frozen_string_literal: true

module ServicioHelper
end

app/helpers/settings_helper.rb
# frozen_string_literal: true

module SettingsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/new_admin.html.erb
<%if current_user.role_id!=2%>
<script type='text/javascript'>
    window.location.href="/";
    window.alert("No tienes permisos");
</script>
<%end%>
<div class="hero is-fullheight is-light is-bold">
    <div class="columns is-centered">
        <div class='column is-one-fifth'>
            <div class='card'>
                <div class='card-content'>
                    <h1 class= "title has-text-centered">Nuevo Admin</h1>
                    <%= form_with model: @user, :url => { :action => :make_admin } do |f| %>
                        <div class='columns is-centered'>
                            <div class='column is-half'>
                                <%= f.label :user, 'Usuario: '%><br>
                                <div class = "select is-info">
                                    <%= f.select :id, @users.collect { |p| [ p.name, p.id ] }, :include_blank => true %>
                                </div>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <div class="card-footer-item">
                                <%= f.submit "Hacer admin", class:'button is-success' %>
                            </div>
                        </footer>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <style>
  .body{
    margin-left: 20px; 
    margin-right: 20px; 
    margin-top: 20px; 
    margin-bottom: 20px; 
  }
  </style>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DCCarrete</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    
    
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <h1 class= "title-is-3"> DCCarrete <h1>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
       <% if user_signed_in? %>
      <%= link_to "Perfil", profile_profile_path, class: "navbar-item"%>
      <%= link_to "Carretes", carretes_index_url, class: "navbar-item"%>
      <%= link_to "Servicios", servicio_index_url, class: "navbar-item"%>
      <% end %>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
      <% if user_signed_in? %>
      <div class="buttons">
      <% if current_user.role_id == 2 %>
        <%= link_to "Settings", settings_path, class: "button is-primary" %>
        <% end %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "button is-light" %>
        <div class="dropdown is-right">
            <div class="dropdown-trigger">
                <button class="button" aria-haspopup="true" aria-controls="dropdown-menu2">
                <span>Notificaciones</span>
                <span class="icon is-small">
                    <i class="fas fa-angle-down" aria-hidden="true"></i>
                </span>
                </button>
            </div>
          <div class="dropdown-menu" id="dropdown-menu2" role="menu">
            <div class="dropdown-content">
            <%if current_user%>
                <% notificaciones = Notification.where(user_id: current_user.id ) %>
                <% if notificaciones%>
                <% notificaciones.each do |element|  %>
                    <%if !element.is_checked%>
                    <div class="dropdown-item">
                        <p> <%= link_to element.n_text, profile_profile_path %> </p>
                        <% element.is_checked = true %>
                        <% element.save%>
                    </div>
                    <hr class="dropdown-divider">
                    <%end%>
                <%end%>
                <%else%>
                <div class="dropdown-item">
                        <p> No tienes notificaciones </p>
                </div>
                <%end%>
            <%end%>
            </div>
        </div>
      </div>
      
      <% else %>
        <div class="buttons">
            <%= link_to "Sign up", new_user_registration_path, class: "button is-primary"%>
          <%= link_to "Sign in", new_user_session_path, class: "button is-light" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

  <body>
    <% flash.each do |type, msg| %>
      <div class="notification is-info">
        <%= msg %>
      </div>
    <% end %>
    
    
    <%= yield %>
  </body>
  <script type="text/javascript">

    var dropdown = document.querySelector('.dropdown');
    dropdown.addEventListener('click', function(event) {
      event.stopPropagation();
      dropdown.classList.toggle('is-active');
    });
  </script>

</html>


app/views/layouts/users.html.haml
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DCCarrete</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= link_to "Home", root_path%>
    <%= link_to "Sign up", new_user_registration_path%>
    <%= link_to "Sign in", new_user_session_path%>
    
    <% if user_signed_in? %>
    
    <%= link_to "config", settings_path%>
    <%= link_to "Carretes", carretes_index_url%>
    <%= link_to "Servicios", servicio_index_url%>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <%= link_to "Perfil", profile_profile_path%>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    
    <%= yield %>
  </body>
  <section class="hero">
  <div class="hero-body">
    <div class="container">
     <div class="columns">
     <div class="column.is-half.is-offset-one-quarter">
     
    </div>
  </div>
</section>



<p>holi</p>
</html>